// Report generation — the client-side equivalent of the source repo's
// reporter/ layer (generator.py, summary_reporter.py, the
// dispute_letter.md.j2 template). v1 produces a dispute letter (Markdown)
// and a findings CSV (via papaparse's unparse, already a dependency for
// ingestion — no extra library needed) rather than the source repo's
// Excel workbook; see ingestion.ts's header comment for why Excel is out
// of scope for now. The branded PDF report (ContractAuditReportDocument.tsx)
// is the flagship downloadable artifact either way.
import Decimal from 'decimal.js';
import Papa from 'papaparse';
import type { AuditResult } from '../types';
import { USE_CASE_PROFILES } from './useCaseConfigs';
import { formatCurrency } from './decimalUtils';

export function generateDisputeLetter(result: AuditResult): string {
  const profile = USE_CASE_PROFILES[result.useCase];
  const disputeFindings = result.findings.filter((f) => f.severity === 'DISPUTE');
  const disputedTotal = disputeFindings.reduce((sum, f) => sum.plus(Decimal.max(f.varianceAmount, 0)), new Decimal(0));
  const today = new Date(result.createdAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  const lines: string[] = [
    `# Dispute Notice — ${profile.displayName}`,
    '',
    `**Date:** ${today}`,
    `**Audit ID:** ${result.auditId}`,
    `**To:** ${profile.recipientRole}`,
    `**Re:** Discrepancies identified in ${profile.domainLabel}`,
    '',
    `This notice identifies ${disputeFindings.length} dispute-grade discrepanc${disputeFindings.length === 1 ? 'y' : 'ies'} between agreed terms and amounts billed, totaling ${formatCurrency(
      disputedTotal
    )} in overcharges. We request review and resolution within **${profile.responseDeadlineDays} days** of this notice.`,
    '',
    '## Disputed Items',
    '',
  ];

  if (disputeFindings.length === 0) {
    lines.push('_No dispute-grade findings were identified in this audit._');
  } else {
    for (const f of disputeFindings) {
      lines.push(`### ${f.itemCode} — ${f.description || '(no description)'}`);
      lines.push('');
      lines.push(`- Agreed: ${formatCurrency(f.agreedAmount)}`);
      lines.push(`- Billed: ${formatCurrency(f.billedAmount)}`);
      lines.push(`- Variance: ${formatCurrency(f.varianceAmount)}`);
      if (f.contractClause) lines.push(`- Contract reference: ${f.contractClause}`);
      if (f.invoiceRef) lines.push(`- Invoice reference: ${f.invoiceRef}`);
      lines.push(`- ${f.explanation}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');
  lines.push(
    '_This notice was generated by an automated variance-detection audit. It is not legal or financial advice — please have it reviewed before relying on it to withhold payment or pursue a formal dispute._'
  );

  return lines.join('\n');
}

export function generateFindingsCsv(result: AuditResult): string {
  const rows = result.findings.map((f) => ({
    'Item Code': f.itemCode,
    Description: f.description,
    'Invoice Ref': f.invoiceRef,
    'Contract Clause': f.contractClause || '',
    'Agreed Amount': f.agreedAmount.toFixed(2),
    'Billed Amount': f.billedAmount.toFixed(2),
    'Variance Amount': f.varianceAmount.toFixed(2),
    'Variance %': f.variancePct ? f.variancePct.toFixed(2) : '',
    'Cap Breached': f.capBreached ? 'Yes' : 'No',
    Severity: f.severity,
    Explanation: f.explanation,
  }));
  return Papa.unparse(rows);
}

export function triggerTextDownload(content: string, fileName: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
}
